<?php

return [
    'TYPE_SCHEDULE_HOLIDAY' => 0,
    'TYPE_SCHEDULE_WEEKLY' => 1,
    
    'TYPE_SCHEDULE_REMOVED' => 0,
    'TYPE_SCHEDULE_UNREMOVED' => 1,
    
    'TYPE_SCHEDULE_DISABLED' => 0,
    'TYPE_SCHEDULE_ENABLED' => 1,
    
    'MAX_CAP_BUS' => 57,

    'TYPE_MAIL_RESERVATION_ADD'         => 0,
    'TYPE_MAIL_RESERVATION_MOVE'        => 1,
    'TYPE_MAIL_RESERVATION_SOFTDELETE'  => 2,
    'TYPE_MAIL_RESERVATION_UPDATE'      => 3,
    'TYPE_MAIL_RESERVATION_REEMAIL'     => 4,
];
